### ISSUE TITLE
Crash during plotting flags 

### ISSUE THREAD

**Issue by TariqBlecher** [ratt-ru/CubiCal#104]
@JSKenyon, this crash happened near the end of the DDE run. Can you reproduce it?
```
22:20:43 - param_db           [P1] [17.2/53.4 47.1/86.9 11.7Gb] wrote 5may-uvcut-4s.ms/BBC-field:0-ddid:None in fragmented 


 - 22:20:48 - main               [0.1/0.2 3.0/3.2 0.0Gb] Time taken for solve and correct residuals: 20368.59411 seconds
 - 22:20:48 - main               [0.1/0.2 3.0/3.2 0.0Gb] computing summary statistinddidcs
 - 22:20:49 - main               [0.3/0.3 3.1/3.2 0.0Gb] saved summary statistics to cubical.stats.pickle
/home/blecher/cubical_venv/local/lib/python2.7/site-packages/numpy/lib/function_base.py:4016: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
 - 22:20:50 - flagging           [0.2/0.3 3.1/3.2 0.0Gb] median chi2 value is nan from 959869 valid t/f slots
 - 22:20:50 - flagging           [0.2/0.3 3.1/3.2 0.0Gb] median count per slot is 4304.0
 - 22:20:51 - flagging           [0.3/0.3 3.1/3.2 0.0Gb] 0 slots (0.00%) flagged on chi2 > 1.2*median
 - 22:20:52 - flagging           [0.3/0.3 3.1/3.2 0.0Gb] 490457 more slots (51.10%) flagged on counts < 0.5*median
 - 22:20:52 - flagging           [0.4/0.4 3.1/3.2 0.0Gb] 0 more channels flagged on density > 0.5
 - 22:20:52 - flagging           [0.4/0.4 3.1/3.2 0.0Gb] 836 more timeslots flagged on density > 0.5
 - 22:20:52 - flagging           [0.4/0.4 3.2/3.2 0.0Gb] 0 more ddids flagged on density > 0.5
 - 22:20:53 - main               [0.4/0.4 3.2/3.2 0.0Gb] Exiting with exception: AttributeError('MaskedConstant' object has no attribute '_fill_value')
 Traceback (most recent call last):
  File "/vault-tina/blecher/J1106/3GC-cubical/CubiCalSrc/CubiCal/cubical/main.py", line 395, in main
    flag3 = flagging.flag_chisq(st, GD, basename, ms.nddid_actual)
  File "/vault-tina/blecher/J1106/3GC-cubical/CubiCalSrc/CubiCal/cubical/flagging.py", line 331, in flag_chisq
    pylab.savefig(filename, DPI=plots.DPI)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 548, in draw
    renderer, renderer.get_image_magnification())
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 774, in make_image
    unsampled=unsampled)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 370, in _make_image
    a_min = np.ma.min(A).astype(scaled_dtype)
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/numpy/ma/core.py", line 3205, in astype
    if self._fill_value is not None:
AttributeError: 'MaskedConstant' object has no attribute '_fill_value'

```

**Comment by o-smirnov** [comment]
This rings so many bells. @JSKenyon, we dealt with something similar before?

**Comment by JSKenyon** [comment]
@o-smirnov Yeah - this is some edge case that occurs when the plots get information which they do not understand. Previously it was when everything was flagged - I must admit that I am not sure that the original fix worked.

**Comment by JSKenyon** [comment]
@TariqBlecher However, if that is failing it is not impossible that you calibration is failing too. Would you mind emailing me your log?

**Comment by JSKenyon** [comment]
For reference, see #72.

**Comment by o-smirnov** [comment]
Our default ``tf-np-median`` setting of 0.5 may perhaps be over-aggressive -- the line below suggests a lot of data is getting flagged "just because". @TariqBlecher may want to run with a setting of 0 to disable this feature:

```
 - 22:20:52 - flagging           [0.3/0.3 3.1/3.2 0.0Gb] 490457 more slots (51.10%) flagged on counts < 0.5*median
```

Oddly, it fails at this plot: https://github.com/ratt-ru/CubiCal/blob/master/cubical/flagging.py#L331, but the fix I put in for #72 is directly above that -- so what's going on? Can you reproduce it with ``--debug-pdb 1``, and poke around in the debugger to see what ``chi2`` contains?

**Comment by JSKenyon** [comment]
I don't currently have access to that MS - worst case scenario I will debug it further on Monday. @TariqBlecher You dE gains are diverging horribly. It is highly likely that the far field dE is really badly behaved, particularly if there are times/frequencies at which it drops below the noise. @o-smirnov Perhaps you could offer some advice, given that you ran into a similar problem in the merger field?

**Comment by TariqBlecher** [comment]
Is this 51% of data excluding data that was flagged prior to running Cubical? 

` - 22:20:52 - flagging           [0.3/0.3 3.1/3.2 0.0Gb] 490457 more slots (51.10%) flagged on counts < 0.5*median
`

I did put a DDE on a source that was very far out (32') where the Half Power Point of the beam is at (13')

**Comment by JSKenyon** [comment]
Will leave it up to @o-smirnov to answer on the flagging front - he is more familiar with that section of code. @TariqBlecher As a sanity check, could you possibly run the calibration again using only the two dE clusters closer to the center? That might also circumvent your bug for now - everything is likely to get buggy when it appears the gains are diverging to NaNs.

**Comment by TariqBlecher** [comment]
Yes, trying that now. I'm also trying with an MS  with less pre-cubical flags.

**Comment by o-smirnov** [comment]
> Is this 51% of data excluding data that was flagged prior to running Cubical?
> ``490457 more slots (51.10%) flagged on counts < 0.5*median``

This is the final flagging step. 51% refers to 51% of intervals not completely flagged prior to running cubical. The threshold is controlled by ``--flags-tf-np-median`` (0.5 by default). What it does is, it looks at the number of valid (i.e. not flagged prior to cubical and not flagged by the solver) visibilities per each time-frequency interval, finds the median value, then flags out intervals where the number of valid baselines drops to less than half that number. 

The reasoning behind this is, if you've got a badly underpopulated solution interval, the solutions for that interval are likely to be crappy anyway, so may as well flag all of it. You can disable this behaviour with ``--flags-tf-np-median 0``, but indeed it does look like the real problem is that your data is over-flagged.

You can think of this step as a very crude version of @ebonnassieux's weights (see also discussion in #85).
