### ISSUE TITLE
BITFLAG freeze (oms-deploy)

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#121]
Anyone seen a freeze following this message before? I'm on the oms-deploy branch.

```
 - 17:17:17 - main               [P1] [17.8/68.6 18.4/80.3 29.7Gb] loading tile #5/7                                                       |
 - 17:17:17 - data_handler       [P1] [17.8/68.6 18.4/80.3 29.7Gb] reading MS rows 289200~361319                                           |
 - 17:18:53 - data_handler       [P1] [35.4/68.6 44.9/80.3 38.5Gb]   reading MODEL_DATA for model 0 direction 0                            |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]   error reading BITFLAG column: not fatal, since we'll auto-fill it from|
 FLAG                                                                                                                                      |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]     Traceback (most recent call last):                                  |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]       File "/home/heywoodl/Software/CubiCal_oms_deploy/CubiCal/cubical/d|
ata_handler.py", line 477, in load                                                                                                         |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]         self.bflagcol = self.handler.fetchslice("BITFLAG", self.first_ro|
w, nrows)                                                                                                                                  |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]       File "/home/heywoodl/Software/CubiCal_oms_deploy/CubiCal/cubical/d|
ata_handler.py", line 1339, in fetchslice                                                                                                  |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]         return self.data.getcol(column, startrow, nrows)                |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]       File "/home/heywoodl/venv/cubienv/local/lib/python2.7/site-package|
s/casacore/tables/table.py", line 951, in getcol                                                                                           |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]         return self._getcol (columnname, startrow, nrow, rowincr)       |
 - 17:21:37 - data_handler       [P1] [63.0/68.6 74.6/80.3 51.8Gb]     RuntimeError: Table DataManager error: Invalid operation: SSMIndColu|
mn::getShape: no array in row 289200 of column BITFLAG in table /data/disk1/meerkat/stripe82/1492064013_wtspec_EQU_COMM_TEST.ms            |
 - 17:21:40 - data_handler       [P1] [67.3/68.6 79.0/80.3 51.8Gb]   auto-filling BITFLAG/BITFLAG_ROW of shape (72120, 4096, 4)
```

**Comment by o-smirnov** [comment]
Hmmm... somehow, I don't think the freeze is related to the message, because the message is pretty much the last thing that happens when a new tile is loaded. Are you sure it's not still solving the previous tile?

**Comment by IanHeywood** [comment]
That 17:21 time stamp is accurate, from yesterday. htop is looking suspiciously quiet.

**Comment by o-smirnov** [comment]
Damn. Is this on a machine I can get access to?

**Comment by IanHeywood** [comment]
I'll scp it to a Rhodes machine. Here's what happened when I Ctrl+C'd it, in case that's informative:

```
^CProcess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/heywoodl/venv/cubienv/local/lib/python2.7/site-packages/concurrent/futures/process.py", line 122, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
KeyboardInterrupt
```

**Comment by IanHeywood** [comment]
This is gonna take a while...

**Comment by IanHeywood** [comment]
What's going on under the hood when it tells me it's "waiting for I/O on tile #X"?

Must be something more sophisticated the usual lock files due to the parallelism?

**Comment by o-smirnov** [comment]
Yeah. It's the main process waiting for the I/O process to tell it that the reading of the tile is complete (so it knows to unleash solver workers on it).

If the MS is file-locked elsewhere (e.g. by a backgrounded cubical, or another process), the I/O process will hang on the lock, and the main process will wait indefinitely.

**Comment by IanHeywood** [comment]
Thanks. It's going now, I was just wondering because sometimes it sits there for a few minutes, sometimes no time at all.

**Comment by o-smirnov** [comment]
What happens is, it tells the I/O thread to start reading tile N+1 at the same time as it starts the solvers on tile N. So it depends on who finishes first.
