### ISSUE TITLE
endResult>=shape

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#144]
I think this might have been me asking it to involve channel 2048 when I should have only gone as far as 2047, but might be a quick and easy fix to cater for the careless user (i.e. me).

Cheers.

```
 - 12:38:49 - cc                 [0.2/0.2 1.3/1.3 0.0Gb] set global console verbosity level 0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] started /mnt/home/ianh/venv/cubical/bin/gocubical cosmos-dEcal.parset --data-ms=1516996832_x16_8s_fg_wtspec_COSMOS.ms --sel-chan=1636~2048 --model-list=MODEL_DATA:DIR1:img_COSMOS3MS_apcalfitsmask_0004_dE-sources.pybdsm.lsm.html@dE --g-save-to={data[ms]}/G-field:{sel[field]}:fchunk4 --de-save-to={data[ms]}/dE-field:{sel[field]}:fchunk4 --out-name cube_dEcal_1516996832_x16_8s_fg_wtspec_COSMOS.ms_2018-02-28-12-38-45_fchunk4
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  Selected Options:
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [data] Visibility data options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ms ................................................ = 1516996832_x16_8s_fg_wtspec_COSMOS.ms
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - column ............................................ = DATA
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - time-chunk ........................................ = 480
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - freq-chunk ........................................ = 410
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - chunk-by .......................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - chunk-by-jump ..................................... = 0.0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - single-chunk ...................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [sel] Data selection options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - field ............................................. = 0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ddid .............................................. = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - taql .............................................. =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - chan .............................................. = 1636~2048
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [model] Calibration model options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - list .............................................. = MODEL_DATA:DIR1:img_COSMOS3MS_apcalfitsmask_0004_dE-sources.pybdsm.lsm.html@dE
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ddes .............................................. = auto
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - beam-pattern ...................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - beam-l-axis ....................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - beam-m-axis ....................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [montblanc] Montblanc simulation options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - device-type ....................................... = CPU
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - dtype ............................................. = float
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - feed-type ......................................... = linear
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - mem-budget ........................................ = 4096
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - verbosity ......................................... = WARNING
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [weight] Weighting options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - column ............................................ = WEIGHT_SPECTRUM
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [flags] Flagging options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - apply ............................................. = legacy
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - auto-init ......................................... = legacy
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - save .............................................. = cubical
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - reinit-bitflags ................................... = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - post-sol .......................................... = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - tf-chisq-median ................................... = 1.2
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - tf-np-median ...................................... = 0.5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - time-density ...................................... = 0.5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - chan-density ...................................... = 0.5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ddid-density ...................................... = 0.5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [sol] Solution options which apply at the solver level
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - jones ............................................. = ['G', 'dE']
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - precision ......................................... = 32
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - delta-g ........................................... = 1e-06
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - delta-chi ......................................... = 1e-06
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - chi-int ........................................... = 5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - last-rites ........................................ = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - stall-quorum ...................................... = 0.99
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - term-iters ........................................ =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - min-bl ............................................ = 0.0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-bl ............................................ = 1000000.0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - subset ............................................ =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [bbc] Options for baseline-based corrections (a.k.a. BBCs, a.k.a. interferometer gains).
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - load-from ......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - compute-2x2 ....................................... = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - apply-2x2 ......................................... = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - save-to ........................................... = {data[ms]}/BBC-field:{sel[field]}-ddid:{sel[ddid]}.parmdb
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - per-chan .......................................... = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - plot .............................................. = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [dist] Parallelization and distribution options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ncpu .............................................. = 6
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - affinity .......................................... = 1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - main-affinity ..................................... = auto
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - min-chunks ........................................ = 10
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [out] Options for output products
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - name .............................................. = cube_dEcal_1516996832_x16_8s_fg_wtspec_COSMOS.ms_2018-02-28-12-38-45_fchunk4
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - mode .............................................. = sr
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - column ............................................ = CORRECTED_DATA
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - model-column ...................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - reinit-column ..................................... = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - subtract-model .................................... = 0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - subtract-dirs ..................................... = :
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - plots ............................................. = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - plots-show ........................................ = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [log] Options related to logging
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - memory ............................................ = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - boring ............................................ = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - append ............................................ = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - verbose ........................................... = 0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - file-verbose ...................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [debug] Debugging options for the discerning masochist
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - pdb ............................................... = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - panic-amplitude ................................... = 0.0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - stop-before-solver ................................ = False
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [misc] Miscellaneous options
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - random-seed ....................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - parset-version .................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [g] Options for G-Jones term
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - solvable .......................................... = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - type .............................................. = complex-2x2
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - load-from ......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - xfer-from ......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - save-to ........................................... = {data[ms]}/G-field:{sel[field]}:fchunk4
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - dd-term ........................................... = 0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - fix-dirs .......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - update-type ....................................... = full
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - time-int .......................................... = 6
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - freq-int .......................................... = 410
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-prior-error ................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-post-error .................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - clip-low .......................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - clip-high ......................................... = 10.0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - clip-after ........................................ = 5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-iter .......................................... = 20
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - conv-quorum ....................................... = 0.99
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ref-ant ........................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - prop-flags ........................................ = default
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - term-iters ........................................ = 10
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] [de] Options for dE-Jones term
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - solvable .......................................... = True
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - type .............................................. = complex-2x2
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - load-from ......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - xfer-from ......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - save-to ........................................... = {data[ms]}/dE-field:{sel[field]}:fchunk4
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - dd-term ........................................... = 1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - fix-dirs .......................................... =
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - update-type ....................................... = full
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - time-int .......................................... = 480
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - freq-int .......................................... = 410
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-prior-error ................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-post-error .................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - clip-low .......................................... = 0.1
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - clip-high ......................................... = 10.0
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - clip-after ........................................ = 5
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - max-iter .......................................... = 20
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - conv-quorum ....................................... = 0.99
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - ref-ant ........................................... = None
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - prop-flags ........................................ = default
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb]  - term-iters ........................................ = 10
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] mode: solve and correct residuals
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb] reading MS 1516996832_x16_8s_fg_wtspec_COSMOS.ms
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   sorting MS by TIME column
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   detected linear (xy) feeds
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   fields are *0: COSMOS
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   MS contains 1 spectral windows of 2048 channels each
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   applying a channel selection of 1636~2048
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   applying TAQL query 'FIELD_ID == 0 && DATA_DESC_ID IN [0]' (122400/122400 rows selected)
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   16 antennas, 122400 rows, 1/1 DDIDs, 900 timeslots, 412 channels per DDID, 2 corrs
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   DDID central frequencies are at 1.63 GHz
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   BITFLAG column found. Will auto-fill with 'legacy' (1) from FLAG/FLAG_ROW if not filled
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]     BITFLAG column defines the following flagsets: legacy:1 cubical:2
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]     Applying flagset(s) legacy
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   Applying BITFLAG mask 1 to input data
 - 12:38:49 - data_handler       [0.2/0.2 1.3/1.3 0.0Gb]   Will save output flags into BITFLAG 'cubical' (2), and into FLAG/FLAG_ROW
 - 12:38:49 - main               [0.2/0.2 1.3/1.3 0.0Gb] Enabling G,dE-Jones
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb] Using 1 model(s) for 4 directions(s)
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   model 0 (weight WEIGHT_SPECTRUM):
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]     direction 0: MODEL_DATA
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]     direction 1: DIR1
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]     direction 2: A004(img_COSMOS3MS_apcalfitsmask_0004_dE-sources.pybdsm.lsm.html)
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]     direction 3: B184(img_COSMOS3MS_apcalfitsmask_0004_dE-sources.pybdsm.lsm.html)
 - 12:38:50 - main               [0.2/0.2 1.4/1.4 0.0Gb] subtraction directions set to slice(None, None, None)
 - 12:38:50 - param_db           [0.2/0.2 1.4/1.4 0.0Gb] creating 1516996832_x16_8s_fg_wtspec_COSMOS.ms/G-field:0:fchunk4 in fragmented mode
 - 12:38:50 - gain_machine       [0.2/0.2 1.4/1.4 0.0Gb] G solutions will be saved to 1516996832_x16_8s_fg_wtspec_COSMOS.ms/G-field:0:fchunk4
 - 12:38:50 - param_db           [0.2/0.2 1.4/1.4 0.0Gb] creating 1516996832_x16_8s_fg_wtspec_COSMOS.ms/dE-field:0:fchunk4 in fragmented mode
 - 12:38:50 - gain_machine       [0.2/0.2 1.4/1.4 0.0Gb] de solutions will be saved to 1516996832_x16_8s_fg_wtspec_COSMOS.ms/dE-field:0:fchunk4
 - 12:38:50 - param_db           [0.2/0.2 1.4/1.4 0.0Gb] creating 1516996832_x16_8s_fg_wtspec_COSMOS.ms/BBC-field:0-ddid:None.parmdb in fragmented mode
 - 12:38:50 - gain_machine       [0.2/0.2 1.4/1.4 0.0Gb] will compute & save suggested baseline-based corrections (BBCs) to 1516996832_x16_8s_fg_wtspec_COSMOS.ms/BBC-field:0-ddid:None.parmdb
 - 12:38:50 - gain_machine       [0.2/0.2 1.4/1.4 0.0Gb]   (these can optionally be applied in a subsequent CubiCal run)
 - 12:38:50 - main               [0.2/0.2 1.4/1.4 0.0Gb] defining chunks (time 480, freq 410)
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   read indexing columns
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   built timeslot index (900 unique timestamps)
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   using 2 freq chunks: 0 410 412
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   found 2 time chunks: 0 480 900
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   generated 2 row chunks based on time and DDID
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   row chunks yield 2 potential tiles
 - 12:38:50 - data_handler       [0.2/0.2 1.4/1.4 0.0Gb]   coarsening this to 1 tiles (min 10 chunks per tile)
 - 12:38:50 - main               [0.2/0.2 1.6/1.6 0.0Gb] waiting for I/O on tile #1/1
 - 12:38:50 - main               [io] [0.1/0.1 1.5/1.5 0.0Gb] loading tile #1/1
 - 12:38:50 - data_handler       [io] [0.1/0.1 1.5/1.5 0.0Gb] tile #1/1: reading MS rows 0~122399
 - 12:38:50 - main               [io] [0.1/0.1 1.5/1.5 0.0Gb] I/O handler for load 0 save None failed with exception: Slicer error:infer: endResult>=shape
 - 12:38:50 - main               [io] [0.1/0.1 1.5/1.5 0.0Gb] Traceback (most recent call last):
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/main.py", line 581, in _io_handler
    tile.load(load_model=load_model)
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/data_handler.py", line 324, in load
    self.handler.data_column, self.first_row, nrows).astype(self.handler.ctype)
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/data_handler.py", line 1405, in fetchslice
    return self.data.getcolslice(column, self._ms_blc, self._ms_trc, [], startrow, nrows)
  File "/mnt/home/ianh/venv/cubical/local/lib/python2.7/site-packages/casacore/tables/table.py", line 1049, in getcolslice
    startrow, nrow, rowincr)
RuntimeError: Slicer error:infer: endResult>=shape
 - 12:38:50 - main               [0.2/0.2 1.6/1.6 0.0Gb] Exiting with exception: RuntimeError(Slicer error:infer: endResult>=shape)
 Traceback (most recent call last):
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/main.py", line 429, in main
    if not done or not io_futures[itile].result():
  File "/mnt/home/ianh/venv/cubical/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/mnt/home/ianh/venv/cubical/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
RuntimeError: Slicer error:infer: endResult>=shape
```

**Comment by IanHeywood** [comment]
Confirmed, it's running now.

**Comment by o-smirnov** [comment]
I agree, the error message is misleading -- we should check for this rather than let casacore spew it's scary and mysterious stuff.
