### ISSUE TITLE
implement on-the-fly rebinning

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#151]
One way to both speed up solutions over large intervals, and reduce RAM pressure, is to average the data on-the-fly by some user-specified factor. This can be done in the I/O thread, transparently to the rest of the process (well, but for some bookkeeping).

Obviously this would only be useful in solve-only mode (need full resolution data to correct or generate proper residuals!), but then the solutions can be applied in a second, apply-only, full-resolution run (with a smaller chunk size, to keep RAM usage down). And for 1GC, we'd be using solve-only to begin with. Also, we can still write out the averaged corrected data or residuals in the first pass -- it can still be a useful diagnostic.

**Comment by o-smirnov** [comment]
By the way, a convenient piece of arithmetic: 64 dishes with 2K channels makes for almost exactly 1GB of visibilities per timeslot (at single precision). Makes it easy to work out what the RAM budgets are for a given solution interval and number of directions...

**Comment by o-smirnov** [comment]
OK, don't look now, but I *think* I have a working version of this on the ``issue-151`` branch. It works, and it does something seemingly sensible with the 3C147 tests I ran.

I'd like to do some more battle-testing before I issue a PR. In the meantime, @IanHeywood and @bennahugo, since you're already in the deep end with MK64 data, care to give this branch a spin? E.g.  ``--data-rebin-time 3`` and ``--data-rebin-freq 4`` will bin 3 timeslots and 4 channels together and either win you a factor of 12, or go down in flames gloriously.

**Comment by o-smirnov** [comment]
Try ``cd CubiCal; python setup.py develop``. That'll cythonize the new rebinning kernel. Not sure why pip install is not picking it up, @JSKenyon needs to take a look at that.

**Comment by IanHeywood** [comment]
Did that (had to specfic a --prefix that I had permissions for), and the executable has been rebuilt, but I get the same error.

**Comment by o-smirnov** [comment]
Python setup.py develop --user, perhaps?

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
Same error...

Love the way testing new features is 90% this shit. 😖

**Comment by o-smirnov** [comment]
Wipe and install from scratch? It's supposed to compile the module to an
.so file and install it somewhere...

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
Tore it down and started again. Both 

```
pip install -U -I -e CubiCal/
```

and 

```
python setup.py build_ext --user
```

gave an error like this:

```
Obtaining file:///users/ianh/Software/CubiCal-151/CubiCal
    Complete output from command python setup.py egg_info:
    INFO:root:Cython is available. Cythonizing...

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

    ctypedef np.uint16_t flag_t

    ctypedef np.int64_t index_t

    ctypdef fused vis_or_flag_t
           ^
    ------------------------------------------------------------

    cubical/kernels/rebinning.pyx:54:8: Syntax error in simple statement list
    Compiling cubical/kernels/rebinning.pyx because it changed.
    [1/1] Cythonizing cubical/kernels/rebinning.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/users/ianh/Software/CubiCal-151/CubiCal/setup.py", line 87, in <module>
        extensions = cythonize(extensions, compiler_directives={'binding': True}, annotate=True)
      File "/users/ianh/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1026, in cythonize
        cythonize_one(*args)
      File "/users/ianh/.local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1146, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: cubical/kernels/rebinning.pyx
```

**Comment by IanHeywood** [comment]
The cython step seemed to work:

```
Singularity kern3.img:~/Software/CubiCal-151/CubiCal> pip install --user cython
Collecting cython
  Downloading https://files.pythonhosted.org/packages/fe/d6/a097bd9913cc0fc974b968f5586d3f0609f46ca58b2aae3b8dfd51c1fe18/Cython-0.28.2-cp27-cp27mu-manylinux1_x86_64.whl (3.3MB)
    100% |################################| 3.3MB 361kB/s
Installing collected packages: cython
Successfully installed cython-0.28.2
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by o-smirnov** [comment]
Can you remove the line with ctypdef? It's an error that snuck in that my
version of cython didn't pick up...

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
From rebinning.pyx?

Line or lines?

```
$ grep ctypedef cubical/kernels/rebinning.pyx
ctypedef np.complex64_t fcomplex
ctypedef np.complex128_t dcomplex
ctypedef fused complex3264:
ctypedef fused float3264:
ctypedef np.float32_t wfloat
ctypedef np.uint16_t flag_t
ctypedef np.int64_t index_t
```

**Comment by o-smirnov** [comment]
The ctypdef one. Without the e, it's misspelled.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
Ah, didn't spot that, sorry.

**Comment by IanHeywood** [comment]
Removed it, and the two indented lines below it. The `pip install -U -I -e CubiCal/` method failed because of a permission error, however `python setup.py build_ext --user` ostensibly completed (with loads of warnings). Same error.

**Comment by o-smirnov** [comment]
Ugh, can you try it on nash?

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
Tried correcting the typo and ran `setup.py...`, that cause a whole host of new errors. 

Will give it a go on nash when my DDF tests are done. 

Cheers.

**Comment by IanHeywood** [comment]
Got a virtualenv working on IDIA, but of course I don't have permission to apt-get anything, and I'm not sure how to get it to pick up any of the dependencies that are installed 'system-wide' as part of the kern-3 singularity image...

I'm out of my depth and out of patience. I'll grumble to someone there about it on Monday, and proceed on nash when there's a gap.

**Comment by o-smirnov** [comment]
Can I log onto your idia account? Bearing in mind we're not members or
anything.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
I think that would violate a whole lotta T&C's.

Which is a shame as it's probably the only way we'll get it working.

**Comment by o-smirnov** [comment]
Well the old version built fine. I'm sure it's just some small niggle.
Let's do a step by step on Monday.



Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by o-smirnov** [comment]
OK, I pushed a fix for the ctypdef error, and also something that ought to address #180. I think the installation woes you were having here are related to that, so could you please git pull this branch, ``rm cubical/kernels/*.{c,cpp}``, and then ``pip install -e CubiCal/`` again?

**Comment by o-smirnov** [comment]
BTW @JSKenyon, I like your idea of naming releases. Once this is tested, it is presumably worthy of another point release. May I humbly suggest "To bin or not to bin" as the name?

**Comment by o-smirnov** [comment]
@IanHeywood probably worth pulling and rebuilding anyway, as further testing found a bookkeeping bug. But otherwise I'm pretty happy with how it works now.

**Comment by IanHeywood** [comment]
Am past the cython issues on the latest issue-151 branch on an IDIA node, but now am getting the following...

```
 - 18:52:33 - data_handler       [0.2/0.2 4.4/5.3 1.5Gb] Using 1 model(s) for 3 directions(s)
 - 18:52:33 - data_handler       [0.2/0.2 4.4/5.3 1.5Gb]   model 0 (weight WEIGHT_SPECTRUM):
 - 18:52:33 - data_handler       [0.2/0.2 4.4/5.3 1.5Gb]     direction 0: MODEL_DATA
 - 18:52:33 - data_handler       [0.2/0.2 4.4/5.3 1.5Gb]     direction 1: DIR1
 - 18:52:33 - data_handler       [0.2/0.2 4.4/5.3 1.5Gb]     direction 2: A010(img_CDFS1nonorm_pcalr0p4_0000_dE-sources.pybdsm.lsm.html)
 - 18:52:33 - main               [0.2/0.2 4.4/5.3 1.5Gb] subtraction directions set to slice(None, None, None)
 - 18:52:33 - param_db           [0.2/0.2 4.4/5.3 1.5Gb] creating 1509215425_CDFS1_fg_wtspec_J033230-280757.ms/G-field:0:fchunk0 in fragmented mode
 - 18:52:33 - gain_machine       [0.2/0.2 4.4/5.3 1.5Gb] G solutions will be saved to 1509215425_CDFS1_fg_wtspec_J033230-280757.ms/G-field:0:fchunk0
 - 18:52:33 - param_db           [0.2/0.2 4.4/5.3 1.5Gb] creating 1509215425_CDFS1_fg_wtspec_J033230-280757.ms/dE-field:0:fchunk0 in fragmented mode
 - 18:52:33 - gain_machine       [0.2/0.2 4.4/5.3 1.5Gb] de solutions will be saved to 1509215425_CDFS1_fg_wtspec_J033230-280757.ms/dE-field:0:fchunk0
 - 18:52:33 - param_db           [0.2/0.2 4.4/5.3 1.5Gb] creating 1509215425_CDFS1_fg_wtspec_J033230-280757.ms/BBC-field:0-ddid:None.parmdb in fragmented mode
 - 18:52:33 - gain_machine       [0.2/0.2 4.4/5.3 1.5Gb] will compute & save suggested baseline-based corrections (BBCs) to 1509215425_CDFS1_fg_wtspec_J033230-280757.ms/BBC-field:0-ddid:None.parmdb
 - 18:52:33 - gain_machine       [0.2/0.2 4.4/5.3 1.5Gb]   (these can optionally be applied in a subsequent CubiCal run)
 - 18:52:33 - main               [0.2/0.2 4.4/5.3 1.5Gb] multi-process mode: 3+1 workers, single thread, unlimited Montblanc threads
 - 18:52:33 - main               [0.2/0.2 4.4/5.3 1.5Gb] defining chunks (time 240, freq 256)
 - 18:52:33 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   read indexing columns (550936 total rows)
 - 18:52:33 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   built timeslot index (4051 unique timestamps)
 - 18:52:33 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   max chunk size is 240 timeslots and/or -- seconds
 - 18:52:33 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   computing time rebinning by 12 timeslots
 - 18:52:33 - main               [0.2/0.2 4.5/5.3 1.5Gb] Exiting with exception: TypeError('NoneType' object is not iterable)
 Traceback (most recent call last):
  File "/users/ianh/Software/CubiCal/cubical/main.py", line 353, in main
    chunks_per_tile=chunks_per_tile, max_chunks_per_tile=GD["dist"]["max-chunks"])
  File "/users/ianh/Software/CubiCal/cubical/data_handler/ms_data_handler.py", line 873, in define_chunk
    for column in chunk_by:
TypeError: 'NoneType' object is not iterable
```

**Comment by o-smirnov** [comment]
OK, that's easy, pull and try again?

**Comment by IanHeywood** [comment]
Next up! :sob:

```
 - 19:03:54 - main               [0.2/0.2 4.4/5.3 1.5Gb] defining chunks (time 240, freq 256)
 - 19:03:54 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   read indexing columns (550936 total rows)
 - 19:03:54 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   built timeslot index (4051 unique timestamps)
 - 19:03:54 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   max chunk size is 240 timeslots and/or -- seconds
 - 19:03:54 - data_handler       [0.2/0.2 4.5/5.3 1.5Gb]   computing time rebinning by 12 timeslots
 - 19:03:55 - data_handler       [0.2/0.3 4.5/5.3 1.5Gb]   found 17 time chunks: 0 240 480 720 960 1200 1440 1680 1920 2160 2400 2640 2880 3120 3360 3600 3840 4051
 - 19:03:55 - data_handler       [0.2/0.3 4.5/5.3 1.5Gb]   will rebin into 45968 rows (338 rebinned timeslots)
 - 19:03:55 - data_handler       [0.2/0.3 4.5/5.3 1.5Gb] WARNING: output columns will be upsampled from time-binned data!
 - 19:03:55 - data_handler       [0.2/0.3 4.5/5.3 1.5Gb]   generated 2 row chunks based on time and DDID
 - 19:03:55 - data_handler       [0.2/0.3 4.5/5.3 1.5Gb]   row chunks yield 2 potential tiles
 - 19:03:55 - data_handler       [0.2/0.3 4.5/5.3 1.5Gb]   coarsening this to 1 tiles (max 2 chunks per tile, based on 3/0 requested)
 - 19:03:55 - main               [io] [0.1/0.1 4.6/4.6 1.5Gb] loading tile #1/1
 - 19:03:55 - data_handler       [io] [0.1/0.1 4.6/4.6 1.5Gb] tile #1/1: reading MS rows 0~550935
 - 19:03:56 - main               [0.2/0.3 4.7/5.3 1.5Gb] waiting for I/O on tile #1/1
 - 19:03:56 - main               [io] [0.1/0.1 4.6/4.6 1.5Gb] I/O handler for load 0 save None failed with exception: MSDataHandler instance has no attribute '_ms_blc'
 - 19:03:56 - main               [io] [0.1/0.1 4.6/4.6 1.5Gb] Traceback (most recent call last):
  File "/users/ianh/Software/CubiCal/cubical/workers.py", line 412, in _io_handler
    tile.load(load_model=load_model)
  File "/users/ianh/Software/CubiCal/cubical/data_handler/ms_tile.py", line 601, in load
    obvis0 = self.dh.fetchslice(self.dh.data_column, subset=table_subset).astype(self.dh.ctype)
  File "/users/ianh/Software/CubiCal/cubical/data_handler/ms_data_handler.py", line 736, in fetchslice
    if self._ms_blc == None:
AttributeError: MSDataHandler instance has no attribute '_ms_blc'
 - 19:03:56 - main               [0.2/0.3 4.7/5.3 1.5Gb] Exiting with exception: AttributeError(MSDataHandler instance has no attribute '_ms_blc')
 Traceback (most recent call last):
  File "/users/ianh/Software/CubiCal/cubical/main.py", line 358, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/users/ianh/Software/CubiCal/cubical/workers.py", line 198, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/users/ianh/Software/CubiCal/cubical/workers.py", line 244, in _run_multi_process_loop
    if not done or not io_futures[itile].result():
  File "/users/ianh/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/users/ianh/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
AttributeError: MSDataHandler instance has no attribute '_ms_blc'
```

**Comment by o-smirnov** [comment]
> - 18:52:33 - main               [0.2/0.2 4.4/5.3 1.5Gb] multi-process mode: 3+1 workers, single thread, unlimited Montblanc threads

Suggest ``--dist-ncpu LARGE --dist-nworker 3`` BTW, this will take advantage of multithreading. Where LARGE is 72 or something.

**Comment by o-smirnov** [comment]
> Next up! ￼

Getting there. Try again? This is top-level debugging by proxy here. :)

**Comment by IanHeywood** [comment]
> Suggest --dist-ncpu LARGE --dist-nworker 3 BTW, this will take advantage of multithreading. Where LARGE is 72 or something.

Ah yeah, forgot to modify that in the parset...

> Getting there. Try again? This is top-level debugging by proxy here. :)

No error yet, I'm just waiting for an I/O lock. I think this MS is crushed under a pile of dead CubiCal processes... 😆

**Comment by o-smirnov** [comment]
Kill them all!

**Comment by IanHeywood** [comment]
```
 - 19:36:37 - main               [io] [0.1/0.1 4.6/4.6 1.5Gb] loading tile #1/5
 - 19:36:37 - data_handler       [io] [0.1/0.1 4.6/4.6 1.5Gb] tile #1/5: reading MS rows 0~130559
 - 19:36:37 - main               [0.2/0.3 4.7/5.3 1.5Gb] waiting for I/O on tile #1/5
 - 19:36:51 - data_handler       [io] [8.2/9.1 13.0/14.1 1.5Gb]   applying solvable baseline cutoff deselects 16320 rows
 - 19:36:51 - data_handler       [io] [8.2/9.1 13.0/14.1 1.5Gb]   12.50% visibilities have been deselected
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]   error reading BITFLAG column: not fatal, since we'll auto-fill it from FLAG
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]     Traceback (most recent call last):
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]       File "/users/ianh/Software/CubiCal/cubical/data_handler/ms_tile.py", line 685, in load
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]         self.bflagcol = self.dh.fetchslice("BITFLAG", subset=table_subset)
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]       File "/users/ianh/Software/CubiCal/cubical/data_handler/ms_data_handler.py", line 738, in fetchslice
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]         return subset.getcolslice(column, self._ms_blc, self._ms_trc, self._ms_incr, startrow, nrows)
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]       File "/usr/lib/python2.7/dist-packages/casacore/tables/table.py", line 1049, in getcolslice
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]         startrow, nrow, rowincr)
 - 19:36:51 - data_handler       [io] [8.5/9.1 13.0/14.1 1.5Gb]     RuntimeError: Table DataManager error: Invalid operation: SSMIndColumn::getShape: no array in row 0 in column BITFLAG of table /scratch/users/ianh/LADUMA_full_pol/CDFS1_DDE/1509215425_CDFS1_fg_wtspec_J033230-280757.ms
 - 19:36:51 - data_handler       [io] [9.0/9.1 13.4/14.1 1.5Gb]   auto-filling BITFLAG/BITFLAG_ROW of shape (130560, 256, 4)
 - 19:36:53 - data_handler       [io] [9.1/9.7 13.6/14.2 1.5Gb]   28.95% input visibilities flagged and/or deselected
 - 19:36:53 - data_handler       [io] [9.1/9.7 13.6/14.2 1.5Gb]   rebinning into 10880 rows and 64 channels
 - 19:36:54 - data_handler       [io] [8.1/9.7 12.7/14.2 1.5Gb]   reading MODEL_DATA for model 0 direction 0
 - 19:37:04 - data_handler       [io] [8.2/10.1 12.7/14.7 1.6Gb]   reading DIR1 for model 0 direction 1
 - 19:37:13 - data_handler       [io] [8.2/10.2 12.7/14.7 1.6Gb]   computing visibilities for img_CDFS1nonorm_pcalr0p4_0000_dE-sources.pybdsm.lsm.html
/users/ianh/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-05-20 19:37:18.679195: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
 - 19:37:19 - main               [io] [5.5/10.2 20.5/23.6 1.6Gb] I/O job(s) complete
 - 19:37:19 - main               [0.2/0.3 4.7/5.3 1.6Gb] submitting solver jobs for tile #1/5
 - 19:37:19 - main               [io] [5.5/10.2 20.6/23.6 1.6Gb] loading tile #2/5
 - 19:37:19 - data_handler       [io] [5.5/10.2 20.6/23.6 1.6Gb] tile #2/5: reading MS rows 130560~261119
 - 19:37:20 - solver             [x03] [0.2/0.2 4.9/5.0 1.6Gb] Solver for tile 0 chunk D0T0F0 failed with exception: could not broadcast input array from shape (1,2,1,16,2,2) into shape (3,20,64,16,2,2)
 - 19:37:20 - solver             [x02] [0.2/0.2 4.9/5.0 1.6Gb] Solver for tile 0 chunk D0T1F0 failed with exception: could not broadcast input array from shape (1,2,1,16,2,2) into shape (3,20,64,16,2,2)
 - 19:37:20 - solver             [x03] [0.2/0.2 4.9/5.0 1.6Gb] Traceback (most recent call last):
  File "/users/ianh/Software/CubiCal/cubical/solver.py", line 713, in run_solver
    corr_vis, stats = solver(vdm, soldict, label, sol_opts)
  File "/users/ianh/Software/CubiCal/cubical/solver.py", line 452, in solve_only
    _, stats = _solve_gains(vdm.gm, vdm.weighted_obser, vdm.weighted_model, vdm.flags_arr, sol_opts, label=label)
  File "/users/ianh/Software/CubiCal/cubical/solver.py", line 134, in _solve_gains
    gm.compute_residual(obser_arr, model_arr, resid_arr)
  File "/users/ianh/Software/CubiCal/cubical/machines/jones_chain_machine.py", line 318, in compute_residual
    g, gh = self.accumulate_gains()
  File "/users/ianh/Software/CubiCal/cubical/machines/jones_chain_machine.py", line 257, in accumulate_gains
    gains[:] = g0
ValueError: could not broadcast input array from shape (1,2,1,16,2,2) into shape (3,20,64,16,2,2)
 - 19:37:20 - solver             [x02] [0.2/0.2 4.9/5.0 1.6Gb] Traceback (most recent call last):
  File "/users/ianh/Software/CubiCal/cubical/solver.py", line 713, in run_solver
    corr_vis, stats = solver(vdm, soldict, label, sol_opts)
  File "/users/ianh/Software/CubiCal/cubical/solver.py", line 452, in solve_only
    _, stats = _solve_gains(vdm.gm, vdm.weighted_obser, vdm.weighted_model, vdm.flags_arr, sol_opts, label=label)
  File "/users/ianh/Software/CubiCal/cubical/solver.py", line 134, in _solve_gains
    gm.compute_residual(obser_arr, model_arr, resid_arr)
  File "/users/ianh/Software/CubiCal/cubical/machines/jones_chain_machine.py", line 318, in compute_residual
    g, gh = self.accumulate_gains()
  File "/users/ianh/Software/CubiCal/cubical/machines/jones_chain_machine.py", line 257, in accumulate_gains
    gains[:] = g0
ValueError: could not broadcast input array from shape (1,2,1,16,2,2) into shape (3,20,64,16,2,2)
```

**Comment by IanHeywood** [comment]
```
 - 20:08:04 - main               [0.2/0.3 4.9/5.3 1.7Gb] finished processing tile #2/5
 - 20:08:04 - main               [0.2/0.3 4.9/5.3 1.7Gb] waiting for I/O on tile #3/5
 - 20:08:05 - main               [0.2/0.3 4.9/5.3 1.7Gb] Exiting with exception: AttributeError(MSDataHandler instance has no attribute '_nchan_orig')
 Traceback (most recent call last):
  File "/users/ianh/Software/CubiCal/cubical/main.py", line 358, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/users/ianh/Software/CubiCal/cubical/workers.py", line 198, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/users/ianh/Software/CubiCal/cubical/workers.py", line 244, in _run_multi_process_loop
    if not done or not io_futures[itile].result():
  File "/users/ianh/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/users/ianh/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
AttributeError: MSDataHandler instance has no attribute '_nchan_orig'
```

**Comment by IanHeywood** [comment]
```
Time taken for solve only: 367.125030041 seconds
```

Sounds promising. Time to apply, image, and compare.

**Comment by o-smirnov** [comment]
I'm a bit puzzled that, if you were in solve-only mode all along, https://github.com/ratt-ru/CubiCal/issues/151#issuecomment-390508658 still tripped you up. That chunk of code deals with writing columns, so should not have been invoked (or was it writing BITFLAG? Or MODEL_DATA?) Can I have a look at the full cubical log from that run?

**Comment by IanHeywood** [comment]
Looks like I've cleared the old logs out, sorry. I can't remember my eye not being drawn to the BITFLAG column error in any run, so I'm guessing it was that...
