### ISSUE TITLE
No module cuphase_only

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#188]
Fresh venv, fresh checkout of master

```
SM: no array in row 567300 of column BITFLAG in /home/hugo/MK_LMC/msdir/1525509459_sdp_l0_1284.full_pol_fg_wtspec_LMC.ms/table.f25
 - 19:21:16 - data_handler       [io] [125.9/130.2 168.5/172.7 92.8Gb]   auto-filling BITFLAG/BITFLAG_ROW of shape (567300, 1024, 4)
 - 19:21:51 - data_handler       [io] [130.7/138.9 170.7/181.5 95.4Gb]   39.15% input visibilities flagged and/or deselected
 - 19:21:56 - main               [io] [18.7/138.9 41.4/181.5 95.4Gb] I/O job(s) complete
 - 19:21:56 - main               [1.3/1.3 4.1/4.2 95.4Gb] Exiting with exception: ImportError(No module named cyphase_only)
 Traceback (most recent call last):
  File "/home/hugo/cubvenv/local/lib/python2.7/site-packages/cubical/main.py", line 353, in main
    stats_dict = workers.run_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/hugo/cubvenv/local/lib/python2.7/site-packages/cubical/workers.py", line 201, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/home/hugo/cubvenv/local/lib/python2.7/site-packages/cubical/workers.py", line 268, in _run_multi_process_loop
    stats = future.result()
  File "/home/hugo/cubvenv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/hugo/cubvenv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
ImportError: No module named cyphase_only

```

**Comment by bennahugo** [comment]
pip install ./CubiCal

**Comment by bennahugo** [comment]
Looks like this does not cause a fatal error in installing with pip?

```
> $ python setup.py build_ext                                                                                             [±master ✓]
INFO:root:Cython unavailable. Using bundled .c and .cpp files.
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running build_ext

```

**Comment by JSKenyon** [comment]
Hey @bennahugo. This happened because the cythonised kernels are no longer in the repo. This was done by @o-smirnov to make commits easier to read. #184 and the release just after should fix the problem. The docs [here](http://cubical.readthedocs.io/en/latest/) already point to the new branch. Non-dev installation is via PyPI, and will include the cythonised kernels. Devs will be expected to satisfy the requirements [here](http://cubical.readthedocs.io/en/latest/installation.html). This was the best compromise I could devise. 

Poking @o-smirnov about PR #184 again.

**Comment by bennahugo** [comment]
ok maybe I should read the fineprint instead of bugging people ;)
