### ISSUE TITLE
chain machine: ValueError: could not broadcast input array from shape foo into shape bar

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/CubiCal#193]
I am trying to reduce a dataset with the same options (more or less - added --out-casa-gaintables=0) since I was getting an error when Cubical tried to export to CASA gaintables.) Now get a new error:

```
Traceback (most recent call last):
  File "/home/kshitij/meerkathi-for-gmrt/meerkathi/meerkathi-for-gmrt-venv/local/lib/python2.7/site-packages/cubical/main.py", line 353, in main
    stats_dict = workers.run_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/kshitij/meerkathi-for-gmrt/meerkathi/meerkathi-for-gmrt-venv/local/lib/python2.7/site-packages/cubical/workers.py", line 201, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/home/kshitij/meerkathi-for-gmrt/meerkathi/meerkathi-for-gmrt-venv/local/lib/python2.7/site-packages/cubical/workers.py", line 268, in _run_multi_process_loop
    stats = future.result()
  File "/home/kshitij/meerkathi-for-gmrt/meerkathi/meerkathi-for-gmrt-venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/kshitij/meerkathi-for-gmrt/meerkathi/meerkathi-for-gmrt-venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
ValueError: could not broadcast input array from shape (1,2,1,61,2,2) into shape (4,22,256,61,2,2)
```

**Comment by JSKenyon** [comment]
This is probably related to #187. Poking @o-smirnov and @bennahugo for thoughts. @KshitijT, could you please post your parset or make it available to us. If the data is a manageable size, it might be helpful to give us access.

**Comment by o-smirnov** [comment]
@KshitijT, this is on a Rhodes machine, correct? Please tell me where, I'd like to run it as you and poke around.

**Comment by o-smirnov** [comment]
Problem is here: https://github.com/ratt-ru/CubiCal/blob/master/cubical/machines/jones_chain_machine.py#L252

Already fixed on my issue-151 and madmax branches, so probably no point fixing master, as the PR is looming. I've already told @KshitijT to try the madmax branch.
