### ISSUE TITLE
Gain transfer giving errors

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/CubiCal#204]
I am trying to transfer gains : 
```
gocubical --data-ms msdir/1532022061-corr-p3-HI.ms   --data-column DATA  --out-column CORRECTED_DATA --weight-column WEIGHT_SPECTRUM  --g-xfer-from output-p3/amp-0.parmdb  --dist-ncpu 30 --out-mode ac
```
I run into the following error:
```
Traceback (most recent call last):
  File "/home/kshitij/CubiCal/cubical/main.py", line 360, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/kshitij/CubiCal/cubical/workers.py", line 205, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/home/kshitij/CubiCal/cubical/workers.py", line 273, in _run_multi_process_loop
    stats = future.result()
  File "/home/kshitij/CubiCal-venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/kshitij/CubiCal-venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
IndexError: index 0 is out of bounds for axis 0 with size 0

```

The idea here is to apply gains over a previously flagged part of data. Could the experts point out where I am messing up?

**Comment by o-smirnov** [comment]
First order of business is to re-run with --dist-ncpu 1, because then you get a more meaningful error dump. And point me to the MS.

**Comment by o-smirnov** [comment]
OK that was a genuine bug, only activated in multi-proc mode.
