### ISSUE TITLE
Cubical running error

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/CubiCal#232]
Any clues what's happening here?

```
Exiting with exception: ImportError(No module named rebinning)
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 355, in main
    chunks_per_tile=chunks_per_tile, max_chunks_per_tile=GD["dist"]["max-chunks"])
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_data_handler.py", line 955, in define_chunk
    rebinning = cubical.kernels.import_kernel("rebinning")
  File "/usr/local/lib/python2.7/dist-packages/cubical/kernels/__init__.py", line 86, in import_kernel
    mod = importlib.import_module("cubical.kernels." + name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named rebinning
```

**Comment by o-smirnov** [comment]
@Athanaseus was just dealing with that... something with a broken release not including the right file...

**Comment by JSKenyon** [comment]
Is this installed directly from PyPI? If so, that version is a little out of date. We are also a bit remiss in fixing the setup.py file when we move stuff around.

**Comment by KshitijT** [comment]
@JSKenyon , yup. I should have mentioned; this is through stimela.
