### ISSUE TITLE
Weird error at end of CubiCal run (sqlite3.OperationalError)

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#248]
I get the following at the end when running CubiCal on IDIA slurm nodes. Doesn't look disastrous but haven't seen it before:

```
 - 14:25:11 - main               [0.8/20.4 4.6/24.2 0.0Gb] Time taken for solve and correct: 5229.10297203 seco
nds
 - 14:25:11 - main               [0.8/20.4 4.6/24.2 0.0Gb] Flagging stats: FLAG:40.59% legacy:40.59% cubi
cal:0.00% DESEL:8.67% IN:43.72% NEW:0.50% OUT:40.59%
 - 14:25:11 - main               [0.8/20.4 4.6/24.2 0.0Gb] computing summary statistics
 - 14:25:11 - main               [0.9/20.4 4.6/24.2 0.0Gb] saved summary statistics to cube_apcal_1523464709_sdp_l0.fu
ll_pol_LO_wtspec_COSMOS_1k.ms_2018-12-30-12-57-14.stats.pickle
 - 14:25:23 - plots              [1.0/20.4 5.0/24.2 0.0Gb] saved plot cube_apcal_1523464709_sdp_l0.full_pol_LO_wtspec_
COSMOS_1k.ms_2018-12-30-12-57-14.noise.tf.png
 - 14:25:35 - plots              [1.1/20.4 5.1/24.2 0.0Gb] saved plot cube_apcal_1523464709_sdp_l0.full_pol_LO_wtspec_
COSMOS_1k.ms_2018-12-30-12-57-14.chi2.tf.png
 - 14:25:36 - plots              [1.0/20.4 5.0/24.2 0.0Gb] saved plot cube_apcal_1523464709_sdp_l0.full_pol_LO_wtspec_
COSMOS_1k.ms_2018-12-30-12-57-14.noise.antchan.png
 - 14:25:38 - plots              [1.0/20.4 5.0/24.2 0.0Gb] saved plot cube_apcal_1523464709_sdp_l0.full_pol_LO_wtspec_
COSMOS_1k.ms_2018-12-30-12-57-14.chi2.antchan.png
 - 14:25:38 - param_db           [1.0/20.4 5.0/24.2 0.0Gb] reading 1523464709_sdp_l0.full_pol_LO_wtspec_COSMOS_1k.ms/B
BC-field_0-ddid_None.parmdb in fragmented mode
 - 14:25:38 - param_db           [1.0/20.4 5.1/24.2 0.0Gb]   loading BBC, shape 282x54x54x2x2
 - 14:25:48 - plots              [1.1/20.4 5.1/24.2 0.0Gb] generating plots for suggested baseline-based corrections (
BBCs)
/users/ianh/.local/lib/python2.7/site-packages/numpy/ma/core.py:479: ComplexWarning: Casting complex values to real di
scards the imaginary part
  fill_value = np.array(fill_value, copy=False, dtype=ndtype)
 - 14:32:21 - plots              [1.2/20.4 5.2/24.2 0.0Gb] saved plot cube_apcal_1523464709_sdp_l0.full_pol_LO_wtspec_
COSMOS_1k.ms_2018-12-30-12-57-14.bbc-diag.png
 - 14:35:10 - plots              [1.5/20.4 5.6/24.2 0.0Gb] saved plot cube_apcal_1523464709_sdp_l0.full_pol_LO_wtspec_
COSMOS_1k.ms_2018-12-30-12-57-14.bbc-diag-ant.png
 - 14:35:10 - main               [1.5/20.4 5.6/24.2 0.0Gb] completed successfully
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 3215, in atexit_operations
    self.history_manager.end_session()
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 580, in end_session
    self.writeout_cache()
  File "<decorator-gen-23>", line 2, in writeout_cache
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 60, in needs_sqlite
    return f(self, *a, **kw)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 786, in writeout_cache
    self._writeout_input_cache(conn)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 770, in _writeout_input_cache
    (self.session_number,)+line)
OperationalError: cannot commit - no transaction is active
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 3215, in atexit_operations
    self.history_manager.end_session()
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 580, in end_session
    self.writeout_cache()
  File "<decorator-gen-23>", line 2, in writeout_cache
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 60, in needs_sqlite
    return f(self, *a, **kw)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 786, in writeout_cache
    self._writeout_input_cache(conn)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 770, in _writeout_input_cache
    (self.session_number,)+line)
OperationalError: cannot commit - no transaction is active
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 3215, in atexit_operations
    self.history_manager.end_session()
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 580, in end_session
    self.writeout_cache()
  File "<decorator-gen-23>", line 2, in writeout_cache
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 60, in needs_sqlite
    return f(self, *a, **kw)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 786, in writeout_cache
    self._writeout_input_cache(conn)
  File "/usr/lib/python2.7/dist-packages/IPython/core/history.py", line 770, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.OperationalError: cannot commit - no transaction is active
```

**Comment by o-smirnov** [comment]
I think it's nothing to do with CubiCal. This message:
``` 
- 14:35:10 - main               [1.5/20.4 5.6/24.2 0.0Gb] completed successfully
```
...is normally the last thing CubiCal logs before exiting. 

The stuff after that comes from an IPython session -- and we don't even use IPython. 

I'm guessing that whatever machinery is responsible for job scheduling is running in IPython. So it calls cubical as an external process, then trips over something (its own feet) after that process exits. Probably mostly harmless.
