### ISSUE TITLE
Table conformance error when exporting CASA gain table

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#258]
Processing a VLA D-config snapshot MS and the step where it exports CASA format gain tables has crashed.

I've disabled the export and it's run to completion.

```
 - 13:34:20 - casa_db_adaptor    [io] [0.2/2.4 1.3/3.8 0.7Gb] Exporting to CASA gaintables
/mnt/home/ianh/Software/CubiCal/cubical/database/parameter.py:676: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output_array = output_array[output_reduction]
/mnt/home/ianh/Software/CubiCal/cubical/database/parameter.py:677: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output_mask  = output_mask[output_reduction]
 - 13:34:20 - main               [io] [0.2/2.4 1.3/3.8 0.7Gb] I/O handler for load None save -1 failed with exception: ScalarColumn::putColumn(Vector&): Table conformance error (#rows mismatch)
 - 13:34:20 - main               [io] [0.2/2.4 1.3/3.8 0.7Gb] Traceback (most recent call last):
  File "/mnt/home/ianh/Software/CubiCal/cubical/workers.py", line 421, in _io_handler
    solver.gm_factory.close()
  File "/mnt/home/ianh/Software/CubiCal/cubical/machines/abstract_machine.py", line 797, in close
    db.close()
  File "/mnt/home/ianh/Software/CubiCal/cubical/database/casa_db_adaptor.py", line 467, in close
    self.__export()
  File "/mnt/home/ianh/Software/CubiCal/cubical/database/casa_db_adaptor.py", line 452, in __export
    casa_caltable_factory.create_B_table(self, "G:gain")
  File "/mnt/home/ianh/Software/CubiCal/cubical/database/casa_db_adaptor.py", line 264, in create_B_table
    t.putcol("TIME", time, startrow=nrowsdd * iddid)
  File "/mnt/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/casacore/tables/table.py", line 1157, in putcol
    self._putcol(columnname, startrow, nrow, rowincr, value)
RuntimeError: ScalarColumn::putColumn(Vector&): Table conformance error (#rows mismatch)
 - 13:34:20 - main               [0.2/0.3 1.4/1.5 0.7Gb] Exiting with exception: RuntimeError(ScalarColumn::putColumn(Vector&): Table conformance error (#rows mismatch))
 Traceback (most recent call last):
  File "/mnt/home/ianh/Software/CubiCal/cubical/main.py", line 363, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/mnt/home/ianh/Software/CubiCal/cubical/workers.py", line 208, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/mnt/home/ianh/Software/CubiCal/cubical/workers.py", line 289, in _run_multi_process_loop
    ms.update_flag_counts(io_futures[-1].result()['flagcounts'])
  File "/mnt/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/mnt/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
RuntimeError: ScalarColumn::putColumn(Vector&): Table conformance error (#rows mismatch)
```

**Comment by IanHeywood** [comment]
Perhaps something to do with antenna 9 being dodgy, all the solutions in the parmdb file for this antenna just have "NoneType" in each SPW.

**Comment by IanHeywood** [comment]
Note that I've got this problem on all VLA datasets I've tried processing recently. Disabling the export of CASA tables gets around it.

**Comment by bennahugo** [comment]
Maybe it does not work with multiple spw data. In any case the test should
pass with the parset provided
