### ISSUE TITLE
unicode error in insertcol

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#281]
Another such bastard:
```
 - 18:23:11 - data_handler       [io] [6.0/30.5 11.3/35.9 24.8Gb]   inserting new column CORRECTED_DATA
 - 18:23:11 - main               [io] [6.0/30.5 11.3/35.9 24.8Gb] I/O handler for load 2 save 0 failed with exception: PycValueHolder: unknown python data type
 - 18:23:11 - main               [io] [6.0/30.5 11.3/35.9 24.8Gb] Traceback (most recent call last):
  File "/home/hugo/venv/local/lib/python2.7/site-packages/cubical/workers.py", line 436, in _io_handler
    tile.save(final=finalize)
  File "/home/hugo/venv/local/lib/python2.7/site-packages/cubical/data_handler/ms_tile.py", line 1149, in save
    added = self.dh._add_column(self.dh.output_column)
  File "/home/hugo/venv/local/lib/python2.7/site-packages/cubical/data_handler/ms_data_handler.py", line 1374, in _add_column
    self.ms.addcols(desc, dminfo)
  File "/home/hugo/venv/local/lib/python2.7/site-packages/casacore/tables/table.py", line 1228, in addcols
    self._addcols(tdesc, dminfo, addtoparent)
RuntimeError: PycValueHolder: unknown python data type
 - 18:23:31 - parallactic_machin [x01] [46.3/123.4 52.4/130.0 24.8Gb] Applying P Jones to sky (precomputed)
 - 19:04:15 - solver             [x01] [109.5/131.0 115.8/139.0 24.8Gb] D0T1F0 (end solve) G: 8 iters, conv 100.00%, d/fl 4.58%, PGE 0.00681, stall 57.68%, chi^2 1.371 -> 1.114 (1.115), noise 0.0882 -> 0.0881
 - 19:10:31 - parallactic_machin [x01] [117.6/138.5 123.9/145.2 29.2Gb] Applying P Jones to corrected data (precomputed)
 - 19:12:29 - main               [1.4/2.2 7.9/8.7 29.8Gb] finished processing tile 1/118
 - 19:12:29 - main               [1.4/2.2 7.9/8.7 29.8Gb] waiting for I/O on tile 2/118
 - 19:12:30 - main               [1.4/2.2 7.9/8.7 29.8Gb] Exiting with exception: RuntimeError(PycValueHolder: unknown python data type)
 Traceback (most recent call last):
  File "/home/hugo/venv/local/lib/python2.7/site-packages/cubical/main.py", line 480, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/hugo/venv/local/lib/python2.7/site-packages/cubical/workers.py", line 210, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/home/hugo/venv/local/lib/python2.7/site-packages/cubical/workers.py", line 270, in _run_multi_process_loop
    if not io_futures[itile].result():
  File "/home/hugo/venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/hugo/venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
RuntimeError: PycValueHolder: unknown python data type
```

**Comment by bennahugo** [comment]
We probably need to go through this class with a fine tooth comb and try find all python-casacore calls. This is really annoying if you're trying to chase telescope bugs with 1T measurement sets...

**Comment by o-smirnov** [comment]
Exact duplicate of #274. And I already had a PR open to fix it: https://github.com/ratt-ru/CubiCal/pull/278

I've run my version through a MeerKAT MS and everything seems to work. 

Why did the column name become a unicode, at least under Python 2? In understand under py3 everything is unicoide?

**Comment by bennahugo** [comment]
I thought you said something about ```Actually let's not merge yet, the last change causes more troubles than it solves...```, so I did not want to merge that. 

I've tested my change on data and it ran through until it eventually crashed out of memory on tile 5/60.

**Comment by bennahugo** [comment]
I needed the fix for this one in the experiment I'm about to do on 16 antenna data

**Comment by o-smirnov** [comment]
> I thought you said something about Actually let's not merge yet, the last change causes more troubles than it solves..., so I did not want to merge that.

I take it back! I take it all back!

The OOM thing is worrying... show me please...

**Comment by bennahugo** [comment]
Not to worry it is #280 screwing me

**Comment by bennahugo** [comment]
I eventually just went with CASA K because it looks like the delay solver is not parallelising very well in any case.
