### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#293]
Again with the stimela container version on some recent MIGHTEE observations. Am guessing an empty data tile but thought this sort of stuff usually got trapped.

```
 - 12:49:12 - data_handler       [17.0/37.6 20.6/39.5 3.5Gb]   reading MODEL_DATA for model 0 direction 0
 - 12:49:12 - data_handler       [17.0/37.6 20.6/39.5 3.5Gb] reading MODEL_DATA
 - 12:49:30 - parallactic_machin [3.4/37.6 9.1/39.5 5.5Gb] Applying P Jones to sky (precomputed)
 - 12:49:51 - solver             [4.3/37.6 5.9/39.5 5.5Gb] D0T74F0 (end solve) G: 20 iters, conv 75.00%, d/fl 20.00%, PGE 0.0491, stall 95.95%, chi^2 1.313 -> 1.308 (1.303), noise 0.257
-> 0.255
 - 12:49:53 - parallactic_machin [4.6/37.6 8.1/39.5 5.8Gb] Applying P Jones to corrected data (precomputed)
 - 12:50:08 - parallactic_machin [13.7/37.6 15.5/39.5 5.8Gb] Applying P Jones to sky (precomputed)
 - 12:50:57 - solver             [17.2/37.6 19.0/39.5 4.6Gb] Solver for tile 37 chunk D0T75F0 failed with exception: 'NoneType' object has no attribute 'ndim'
 - 12:50:57 - solver             [17.2/37.6 19.0/39.5 4.6Gb] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/solver.py", line 806, in run_solver
    flag_allocator=allocate_flag_array)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 1032, in get_chunk_cubes
    allocator=allocator)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 301, in _column_to_cube
    col_ndim = column.ndim
AttributeError: 'NoneType' object has no attribute 'ndim'
 - 12:50:57 - main               [17.2/37.6 19.0/39.5 4.6Gb] Exiting with exception: AttributeError('NoneType' object has no attribute 'ndim')
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 480, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 212, in run_process_loop
    return _run_single_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 349, in _run_single_process_loop
    solver.run_solver(solver_type, itile, key, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/solver.py", line 806, in run_solver
    flag_allocator=allocate_flag_array)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 1032, in get_chunk_cubes
    allocator=allocator)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 301, in _column_to_cube
    col_ndim = column.ndim
AttributeError: 'NoneType' object has no attribute 'ndim'
```

**Comment by o-smirnov** [comment]
Damn you're not having a good data processing day, are you?

**Comment by IanHeywood** [comment]
You should see the mystery stuff I'm not reporting because I have no idea what's causing it.

**Comment by bennahugo** [comment]
Hmm wild speculation but it may be nothing in model data (column to cube?). This can happen if you ran something that created a MODEL_DATA column without initializing all fields and then only filled one of the fields. Can you please run CASA clearcal to verify that your columns are properly initialized.

This problem may also point to you using the wrong field id though?

**Comment by o-smirnov** [comment]
No it's the weight column. But may be related to previous shm weirdness.
I'm looking into it.

Cheers,
Oleg

---
Sent from my phone. Quaint into it intolity of spelling inversely
proportional to finger size.

**Comment by IanHeywood** [comment]
Thanks both.

This is a single source MS, model column was filled with wsclean (in predict mode following BDA run). Flagging is (as usual) rather brutal, but the model data look sane.

I've never seen any use in the `clearcal` task, and as such I've never used it. Convince me otherwise?

**Comment by bennahugo** [comment]
Its  useful when you have run setjy and want to subsequently use model_data / used meqtrees turbosim to predict into model_data and then want to flux scale on other fields, etc...

Ok if Oleg is on it good :)
