### ISSUE TITLE
Robust solver can't be chained for DD solving

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#299]
This happens for diag-only = 1 in both g and dd gains. I will test it for diag-only 0
```
 - 13:07:30 - solver             [9.6/27.8 26.8/433.2 16.2Gb] Traceback (most recent call last):
  File "/home/hugo/DEEP2_workspace/CubiCal/cubical/solver.py", line 801, in run_solver
    allocate_vis_array, allocate_flag_array, _ = gm_factory.determine_allocators()
TypeError: 'type' object is not iterable
 - 13:07:30 - main               [9.6/27.8 26.8/433.2 16.2Gb] Exiting with exception: TypeError('type' object is not iterable)
 Traceback (most recent call last):
  File "/home/hugo/DEEP2_workspace/CubiCal/cubical/main.py", line 482, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/hugo/DEEP2_workspace/CubiCal/cubical/workers.py", line 212, in run_process_loop
    return _run_single_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/hugo/DEEP2_workspace/CubiCal/cubical/workers.py", line 349, in _run_single_process_loop
    solver.run_solver(solver_type, itile, key, solver_opts, debug_opts)
  File "/home/hugo/DEEP2_workspace/CubiCal/cubical/solver.py", line 801, in run_solver
    allocate_vis_array, allocate_flag_array, _ = gm_factory.determine_allocators()
TypeError: 'type' object is not iterable

> /home/hugo/DEEP2_workspace/CubiCal/cubical/solver.py(801)run_solver()
    800         # need to know which kernel to use to allocate visibility and flag arrays
--> 801         allocate_vis_array, allocate_flag_array, _ = gm_factory.determine_allocators()
    802 

ipdb> gm_factory
<cubical.machines.jones_chain_robust_machine.Factory object at 0x7f1f94875190>
ipdb> gm_factory.determine_allocators()
<type 'exceptions.NotImplementedError'>
ipdb> gm_factory.determine_allocators()
<type 'exceptions.NotImplementedError'>
ipdb> exit
```

**Comment by bennahugo** [comment]
On further chatting to @JSKenyon it seems the robust solver can't be used on a chain (ie. G + DD jones)

**Comment by JSKenyon** [comment]
Yes - I see that I mentioned this in a commit message. The robust chain was not working prior to me branching off to work on the numba kernels. @ulricharmel please merge master into your branch again. We can then test it out and see if it can finally be merged.

**Comment by bennahugo** [comment]
Alright I believe the PR addresses this. I'm going to close for now and comment further on the PR
