### ISSUE TITLE
No module named rebinning

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#314]
First time trying a `pip -e` installation post-cython. Looks like it's picking up the executable from my virtualenv as expected, but then this happens:

```
 - 11:52:38 - main               | reading defaults from /ceph/pipelines/ianh/MIGHTEE/CDFS/CDFS_2_4/venv_parset_bin.parset
 - 11:52:38 - cc                 [0.1/0.1 1.5/1.5 0.0Gb] set global console verbosity level 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] started /users/ianh/venv/cubical/bin/gocubical /ceph/pipelines/ianh/MIGHTEE/CDFS/CDFS_2_4/venv_parset_bin
.parset --data-ms=1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS_2_4.ms --out-name=cube_pcal_1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS_2_4.ms_CUBEVENV
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  Selected Options:
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [data] Visibility data options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - ms ................................................ = 1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS
_2_4.ms
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - column ............................................ = DATA
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - time-chunk ........................................ = 512
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - freq-chunk ........................................ = 1024
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - rebin-time ........................................ = 8
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - rebin-freq ........................................ = 16
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - chunk-by .......................................... = SCAN_NUMBER
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - chunk-by-jump ..................................... = 1.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - single-chunk ...................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - single-tile ....................................... = -1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [sel] Data selection options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - field ............................................. = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - ddid .............................................. = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - taql .............................................. =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - chan .............................................. =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - diag .............................................. = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [model] Calibration model options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - list .............................................. = MODEL_DATA
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - ddes .............................................. = auto
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - beam-pattern ...................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - beam-l-axis ....................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - beam-m-axis ....................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - feed-rotate ....................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - pa-rotate ......................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [montblanc] Montblanc simulation options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - device-type ....................................... = CPU
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - dtype ............................................. = float
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - feed-type ......................................... = linear
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - mem-budget ........................................ = 1024
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - verbosity ......................................... = WARNING
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - threads ........................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - pa-rotate ......................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [weight] Weighting options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - column ............................................ = WEIGHT_SPECTRUM
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - fill-offdiag ...................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - legacy-v1-2 ....................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [flags] General flagging options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - apply ............................................. = -cubical
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - auto-init ......................................... = legacy
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - save .............................................. = cubical
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - save-legacy ....................................... = auto
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - reinit-bitflags ................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - warn-thr .......................................... = 0.3
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - see-no-evil ....................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [postmortem] Options for "postmortem" flagging based on solution statistics
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - enable ............................................ = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - tf-chisq-median ................................... = 1.2
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - tf-np-median ...................................... = 0.5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - time-density ...................................... = 0.5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - chan-density ...................................... = 0.5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - ddid-density ...................................... = 0.5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [madmax] Options for the "Mad Max" flagger
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - enable ............................................ = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - estimate .......................................... = corr
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - diag .............................................. = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - offdiag ........................................... = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - threshold ......................................... = [0, 20]
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - global-threshold .................................. = [0, 12]
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - plot .............................................. = 1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - plot-frac-above ................................... = 0.01
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - residuals ......................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - plot-bl ........................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - flag-ant .......................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - flag-ant-thr ...................................... = 5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [sol] Solution options which apply at the solver level
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - jones ............................................. = G
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - precision ......................................... = 32
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - delta-g ........................................... = 1e-06
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - delta-chi ......................................... = 1e-06
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - chi-int ........................................... = 5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - last-rites ........................................ = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - stall-quorum ...................................... = 0.99
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - diag-diag ......................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - term-iters ........................................ =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - min-bl ............................................ = 150.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - max-bl ............................................ = 1000000000.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - subset ............................................ =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [bbc] Options for baseline-based corrections (a.k.a. BBCs, a.k.a. interferometer gains).
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - load-from ......................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - compute-2x2 ....................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - apply-2x2 ......................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - save-to ........................................... = {out[name]}-BBC-field_{sel[field]}-ddid_{sel[ddi
d]}.parmdb
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - per-chan .......................................... = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - plot .............................................. = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [dist] Parallelization and distribution options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - ncpu .............................................. = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - nworker ........................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - nthread ........................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - max-chunks ........................................ = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - min-chunks ........................................ = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - pin ............................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - pin-io ............................................ = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - pin-main .......................................... = io
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [out] Options for output products
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - name .............................................. = cube_pcal_1561266559_sdp_l0.full_1284.full_pol_w
tspec_CDFS_2_4.ms_CUBEVENV
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - mode .............................................. = so
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - column ............................................ = CORRECTED_DATA
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - model-column ...................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - reinit-column ..................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - subtract-model .................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - subtract-dirs ..................................... = :
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - plots ............................................. = 1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - casa-gaintables ................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - overwrite ......................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - derotate .......................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - weight-column ..................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [log] Options related to logging
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - memory ............................................ = True
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - boring ............................................ = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - append ............................................ = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - verbose ........................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - file-verbose ...................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - stats ............................................. = chi2:.3f
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - stats-warn ........................................ = chi2:10
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [debug] Debugging options for the discerning masochist
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - pdb ............................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - panic-amplitude ................................... = 0.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - stop-before-solver ................................ = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - escalate-warnings ................................. = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [misc] Miscellaneous options
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - random-seed ....................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - parset-version .................................... = 0.1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [g] Options for G-Jones term
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - solvable .......................................... = 1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - type .............................................. = phase-diag
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - load-from ......................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - xfer-from ......................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - save-to ........................................... = {out[name]}-{JONES}-field_{sel[field]}-ddid_{sel
[ddid]}.parmdb
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - dd-term ........................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - fix-dirs .......................................... =
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - diag-diag ......................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - update-type ....................................... = full
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - time-int .......................................... = 8
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - freq-int .......................................... = 256
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - max-prior-error ................................... = 1000000
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - max-post-error .................................... = 1000000
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - clip-low .......................................... = 0.1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - clip-high ......................................... = 10.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - clip-after ........................................ = 5
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - max-iter .......................................... = 20
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - conv-quorum ....................................... = 0.99
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - ref-ant ........................................... = None
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - prop-flags ........................................ = default
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - epsilon ........................................... = 1e-06
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - delta-chi ......................................... = 1e-06
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - estimate-pzd ...................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - diag-only ......................................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - offdiag-only ...................................... = False
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - robust-cov ........................................ = compute
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - robust-npol ....................................... = 2
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - robust-int ........................................ = 1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - robust-save-weights ............................... = 0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] [de] de
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - dd-term ........................................... = 1
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - clip-low .......................................... = 0.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - clip-high ......................................... = 0.0
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb]  - delta-chi ......................................... = 1e-05
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] Enabling G-Jones
 - 11:52:38 - main               [0.1/0.1 1.5/1.5 0.0Gb] mode: solve only
 - 11:52:38 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb] reading MS 1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS_2_4.ms
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]   detected linear (xy) feeds
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]   fields are *0: CDFS_2_4
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]   MS contains 1 spectral windows
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]   max freq chunk size is 1024 channels and/or -- MHz
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]   rebinning by 16 channels
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]   DDID 0: 1024/1024 selected channels will be rebinned into 64 channels
 - 11:52:42 - data_handler       [0.1/0.1 1.5/1.5 0.0Gb]     found 1 frequency chunks: 0 64
 - 11:53:00 - data_handler       [0.1/0.2 1.5/1.6 0.0Gb]   applying TAQL query 'FIELD_ID == 0 && DATA_DESC_ID IN [0]' (6148044/6148044 rows selected)
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]   62 antennas, 6148044 rows, 1/1 DDIDs, 3148 timeslots, 4 corrs
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]   DDID central frequencies are at 1.29 GHz
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb] WARNING: output columns will be upsampled from frequency-binned data!
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]   BITFLAG column found. Will auto-fill with 'legacy' (1) from FLAG/FLAG_ROW if not filled
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]     BITFLAG column defines the following flagsets: legacy:1 cubical:2
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]     Excluding flagset cubical
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]   Applying BITFLAG mask 1 to input data
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]   Will save output flags into BITFLAG 'cubical' (2), and into FLAG/FLAG_ROW
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb] Using 1 model(s) for 1 directions(s) (DDEs explicitly disabled)
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]   model 0 (weight WEIGHT_SPECTRUM):
 - 11:53:00 - data_handler       [0.1/0.2 1.6/1.6 0.0Gb]     direction 0: MODEL_DATA
 - 11:53:00 - main               [0.1/0.2 1.6/1.6 0.0Gb] subtraction directions set to slice(None, None, None)
 - 11:53:00 - param_db           [0.1/0.2 1.6/1.6 0.0Gb] creating cube_pcal_1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS_2_4.ms_CUBEVENV-G-field_0-ddid_None.p
armdb in fragmented mode
 - 11:53:00 - gain_machine       [0.1/0.2 1.6/1.6 0.0Gb] G solutions will be saved to cube_pcal_1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS_2_4.ms_CUBEVENV-G
-field_0-ddid_None.parmdb
 - 11:53:00 - param_db           [0.1/0.2 1.6/1.6 0.0Gb] creating cube_pcal_1561266559_sdp_l0.full_1284.full_pol_wtspec_CDFS_2_4.ms_CUBEVENV-BBC-field_0-ddid_None
.parmdb in fragmented mode
 - 11:53:00 - gain_machine       [0.1/0.2 1.6/1.6 0.0Gb] will compute & save suggested baseline-based corrections (BBCs) to cube_pcal_1561266559_sdp_l0.full_1284.
full_pol_wtspec_CDFS_2_4.ms_CUBEVENV-BBC-field_0-ddid_None.parmdb
 - 11:53:00 - gain_machine       [0.1/0.2 1.6/1.6 0.0Gb]   (these can optionally be applied in a subsequent CubiCal run)
 - 11:53:00 - main               [0.1/0.2 1.6/1.6 0.0Gb] single-process, single-thread mode
 - 11:53:00 - main               [0.1/0.2 1.6/1.6 0.0Gb] defining chunks (time 512, freq 1024, also when SCAN_NUMBER jumps > 1.0)
 - 11:53:29 - data_handler       [0.3/0.3 1.8/1.8 0.0Gb]   read indexing columns (6148044 total rows)
 - 11:53:31 - data_handler       [0.4/0.4 1.8/1.9 0.0Gb]   built timeslot index (3148 unique timestamps)
 - 11:53:31 - data_handler       [0.4/0.4 1.8/1.9 0.0Gb]   max chunk size is 512 timeslots and/or -- seconds
 - 11:53:31 - data_handler       [0.4/0.4 1.8/1.9 0.0Gb]   computing time rebinning by 8 timeslots
 - 11:53:31 - main               [0.4/0.4 1.8/1.9 0.0Gb] Exiting with exception: ImportError(No module named rebinning)
 Traceback (most recent call last):
  File "/users/ianh/venv/cubical/local/lib/python2.7/site-packages/cubical/main.py", line 355, in main
    chunks_per_tile=chunks_per_tile, max_chunks_per_tile=GD["dist"]["max-chunks"])
  File "/users/ianh/venv/cubical/local/lib/python2.7/site-packages/cubical/data_handler/ms_data_handler.py", line 955, in define_chunk
    rebinning = cubical.kernels.import_kernel("rebinning")
  File "/users/ianh/venv/cubical/local/lib/python2.7/site-packages/cubical/kernels/__init__.py", line 86, in import_kernel
    mod = importlib.import_module("cubical.kernels." + name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named rebinning
```

**Comment by IanHeywood** [comment]
Let's chalk this one up to user incompetence, with a dash of "someone should double check the cubical.readthedocs.io pages".

Cheers.

**Comment by IanHeywood** [comment]
Indeed, I'm wondering if all my recent woes are simply version-related.

The `pip install cubical` that resulted in the above obviously gave me a pre-rebinning version (so pretty ancient).

The stimela cubical-1.1.5.simg that I've been running with on IDIA recently to try to circumvent the venv hassles contains version 1.2.3.

The dev build from the current master is 1.3.0.

Tests pending with 1.3.0 to see if https://github.com/ratt-ru/CubiCal/issues/311 is all related to this, which in my book would be a Good Outcome.

**Comment by IanHeywood** [comment]
Actually, before I commence, I notice master is about a month old. Is there a more recent branch that you recommend?

Cheers.

**Comment by IanHeywood** [comment]
> Tests pending with 1.3.0 to see if #311 is all related to this, which in my book would be a Good Outcome.

Wishful thinking.

https://github.com/ratt-ru/CubiCal/issues/311#issuecomment-526665021
