### ISSUE TITLE
Cubical silently hangs itself on out of memory

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#319]
Hung itself and have been in that state for days. I guess all of this will go away when we switch to the pure threading model and got rid of the dreaded shared memory @JSKenyon 
```
    reqdims=8, allocator=allocator)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 319, in _column_to_cube
    out_arr0 = allocator(out_shape, dtype)
  File "cubical/kernels/includes/phase_kernel.pxi", line 42, in cubical.kernels.cyphase_only_omp.allocate_vis_array
    return cubical.kernels.allocate_reordered_array(shape, dtype, _model_axis_layout, zeros=zeros)
  File "/usr/local/lib/python2.7/dist-packages/cubical/kernels/__init__.py", line 40, in allocate_reordered_array
    array = (np.zeros if zeros else np.empty)(_intrinsic_shape, dtype=dtype)
MemoryError
 - 08:39:48 - solver             [x03] [56.4/65.8 124.7/124.7 172.0Gb] Solver for tile 0 chunk D0T2F0 failed with exception: 
 - 08:39:48 - solver             [x03] [56.4/65.8 124.7/124.7 172.0Gb] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/solver.py", line 806, in run_solver
    flag_allocator=allocate_flag_array)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 1024, in get_chunk_cubes
    reqdims=8, allocator=allocator)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 319, in _column_to_cube
    out_arr0 = allocator(out_shape, dtype)
  File "cubical/kernels/includes/phase_kernel.pxi", line 42, in cubical.kernels.cyphase_only_omp.allocate_vis_array
    return cubical.kernels.allocate_reordered_array(shape, dtype, _model_axis_layout, zeros=zeros)
  File "/usr/local/lib/python2.7/dist-packages/cubical/kernels/__init__.py", line 40, in allocate_reordered_array
    array = (np.zeros if zeros else np.empty)(_intrinsic_shape, dtype=dtype)
MemoryError
 - 08:39:49 - solver             [x02] [84.7/84.7 152.9/152.9 172.0Gb] Solver for tile 0 chunk D0T1F0 failed with exception: 
 - 08:39:49 - solver             [x02] [84.7/84.7 152.9/152.9 172.0Gb] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/solver.py", line 806, in run_solver
    flag_allocator=allocate_flag_array)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 1024, in get_chunk_cubes
    reqdims=8, allocator=allocator)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 351, in _column_to_cube
    out_arr[tuple(cub_selection)] = colsel.conj()[..., (0, 2, 1, 3)]
MemoryError
```

**Comment by KshitijT** [comment]
@bennahugo , is there any update on this issue? I am seeing it as well while reducing some MeerKAT data. I guess temporary solution is to reduce the solution intervals?

**Comment by bennahugo** [comment]
I think this is a issue for version 2 to fix. Not sure if Jon will write something to cull the process pool

**Comment by KshitijT** [comment]
What can be done for now?

**Comment by JSKenyon** [comment]
You could try running it under Python3 - @o-smirnov has informed me that older versions of Python lacked a mechanism to report a non-clean process death. While this might not solve you issue (there will be fundamental limits on your chunks size/number of concurrent processes based on the hardware on which you are running), it might at least replace silent hanging with loud screaming.

**Comment by KshitijT** [comment]
This is through meerkathi, in a python 3 environment. I can cut down on my chunk size but not too much on chunk numbers (it's 2 !). What I am keen on is the calibration going through, I don't mind the silent hanging too much at the moment.

**Comment by bennahugo** [comment]
a python 3 environment does not mean the containers runs python3. you will need to rebuild them to run cubical using python 3

**Comment by KshitijT** [comment]
This is a stimela issue then.

**Comment by o-smirnov** [comment]
Well maybe @SpheMakh can comment, what's the CubiCal cab running, py2 or py3?

@KshitijT is the MS/parset on the RATT cluster somewhere? I'd like to run it for myself to benchmark memory use.

**Comment by KshitijT** [comment]
@o-smirnov it is on Ilifu - it's around 150 MHz bandwidth , 1.5 hours of data, integration time 2 seconds, if that helps?

**Comment by o-smirnov** [comment]
Ahhh, ilifu, same memory issues as @IanHeywood perhaps?

**Comment by IanHeywood** [comment]
I've had zero success running CubiCal with just about any useful level of parallelisation on IDIA hardware since maybe March or April. Lots of people got involved trying to figure it out, but I've basically given up on it.
