### ISSUE TITLE
ImportError when DDFacet is not installed

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#347]
I get the following:

```
 Traceback (most recent call last):
  File "/home/jonathan/CubiCal/cubical/data_handler/DDFacetSim.py", line 9, in <module>
    from DDFacet.Imager import ClassDDEGridMachine
ModuleNotFoundError: No module named 'DDFacet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonathan/CubiCal/cubical/main.py", line 540, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/jonathan/CubiCal/cubical/workers.py", line 216, in run_process_loop
    return _run_single_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/jonathan/CubiCal/cubical/workers.py", line 364, in _run_single_process_loop
    tile.release()
  File "/home/jonathan/CubiCal/cubical/data_handler/ms_tile.py", line 1366, in release
    from .DDFacetSim import cleanup_degridders
  File "/home/jonathan/CubiCal/cubical/data_handler/DDFacetSim.py", line 19, in <module>
    raise ImportError("Could not import DDFacet")
ImportError: Could not import DDFacet
```

This is with Python 3.6.9 with `lsm-support` installed but not `degridder-support`.

**Comment by bennahugo** [comment]
That is on the release which should only be invoked at the end?

**Comment by JSKenyon** [comment]
It happens before any solver messages are emitted. But I think it is happening at the end of the first tile read.

**Comment by bennahugo** [comment]
hmm ok that is not the intended behaviour in any case - the pools should not be shutdown unless it is the last tile
