### ISSUE TITLE
Solving with high verbosity fails with format string

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#373]
```
# ERROR     12:31:56 - solver             [x05] [1.3/7.6 9.3/16.2 15.7Gb] Solver for tile 0 chunk D0T0F153 failed with exception: unsupported format string passed to numpy.ndarray.__format__
# INFO      12:31:56 - solver             [x05] [1.3/7.6 9.3/16.2 15.7Gb] Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 904, in run_solver
#     corr_vis = solver_machine.run()
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 742, in run
#     SolveOnly.run(self)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 711, in run
#     self.sol_opts, label=self.label)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/solver.py", line 101, in _solve_gains
#     gm.precompute_attributes(obser_arr, model_arr, flags_arr, inv_var_chan)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/machines/jones_chain_machine.py", line 128, in precompute_attributes
#     term.precompute_attributes(data_arr, model_arr, flags_arr, inv_var_chan)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/machines/complex_2x2_machine.py", line 188, in precompute_attributes
#     super(Complex2x2Gains, self).precompute_attributes(data_arr, model_arr, flags_arr, noise)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/machines/interval_gain_machine.py", line 500, in precompute_attributes
#     self._report_gain_flags(low_snr, "on low SNR", "your max-prior-error settings", self.low_snr_warn)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/machines/interval_gain_machine.py", line 556, in _report_gain_flags
#     str(d), percflagged[d]) for d in bad_dirs]),
#   File "/usr/local/lib/python3.6/dist-packages/cubical/machines/interval_gain_machine.py", line 556, in <listcomp>
#     str(d), percflagged[d]) for d in bad_dirs]),
# TypeError: unsupported format string passed to numpy.ndarray.__format__

```

**Comment by JSKenyon** [comment]
I am struggling to reproduce this locally, although I think I have seen it before. Could you supply the data and parset? Or would you prefer to fix it yourself? I suspect it is just an edge case, possibly when a chunk is empty or the like.

**Comment by o-smirnov** [comment]
Duplicated more recently in https://github.com/ratt-ru/CubiCal/issues/434.
