### ISSUE TITLE
Another BrokenProcessPool when using a tigger a LSM

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/CubiCal#444]
This only happens when I use a tigger-lsm, suggesting the issue may be in montblanc. When I used MeqTrees to predict and specified a visibility model, the problem went away with all the parameters unchanged.

```bash
# INFO      12:35:08 - ms_tile            [io] [1.1/1.3 3.4/5.7 4.0Gb]   computing visibilities for /stimela_mount/output/meerkat-hydra-selfcal-0-skymodel.lsm.html
# INFO      12:35:25 - main               [0.2 2.3 4.0Gb] Exiting with exception: BrokenProcessPool(A process in the process pool was terminated abruptly while the future was running or pending.)
#  Traceback (most recent call last):
#   File "/usr/local/lib/python3.6/dist-packages/cubical/main.py", line 578, in main
#     stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 226, in run_process_loop
#     return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts, out_opts)
#   File "/usr/local/lib/python3.6/dist-packages/cubical/workers.py", line 286, in _run_multi_process_loop
#     if not io_futures[itile].result():
#   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
#     return self.__get_result()
#   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
#     raise self._exception
# concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

The full log is at https://pastebin.com/QknXvYAF

**Comment by o-smirnov** [comment]
Could you re-run in serial mode (``--dist-ncpu 1``), on the odd chance that we get something more informative out of it before it dies?

**Comment by SpheMakh** [comment]
@sjperkins any ideas on how to fix this?

**Comment by o-smirnov** [comment]
How many sources are there in your LSM?

**Comment by o-smirnov** [comment]
Drop the time chunk down to 10 btw (your time-int is 10 anyway), maybe Montblanc is simply running out of memory?

**Comment by SpheMakh** [comment]
![only two](https://media.giphy.com/media/e7UfwgWAvnGkSY32WN/giphy.gif)

**Comment by sjperkins** [comment]
> More info when running in serial.
> 
> ```shell
> # 2021-03-10 19:38:37.962644: W tensorflow/core/framework/allocator.cc:101] Allocation of 86999040 exceeds 10% of system memory.
> # 2021-03-10 19:38:38.064214: W tensorflow/core/framework/allocator.cc:101] Allocation of 173998080 exceeds 10% of system memory.
> # 2021-03-10 19:38:38.252604: W tensorflow/core/framework/allocator.cc:101] Allocation of 173998080 exceeds 10% of system memory.
> # 2021-03-10 19:38:38.461049: W tensorflow/core/framework/allocator.cc:101] Allocation of 173998080 exceeds 10% of system memory.
> ```

Yes, this seems to be a case of tensorflow *warning* about memory allocations. I don't think the above are errors in their own right: 173998080 is 0.174GB which doesn't seem excessive to me.

https://stackoverflow.com/questions/53639067/tensorflow-cpu-memory-problem-allocation-exceeds-10-of-system-memory

The standard solution is to fix the batch (chunk) size, which @o-smirnov has suggested. https://stackoverflow.com/a/56851691. Have you had any success with this by modifying the Cubical chunking parameters? Otherwise, Cubical may need to subdivide the data into finer chunks before feeding it into Montblanc.

Cut and pasting from the stackoverflow question

```bash
2018-12-05 19:20:44.932780: W tensorflow/core/framework/allocator.cc:122] Allocation of 3359939800 exceeds 10% of system memory.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abandon (core dumped)
```

Do you see any log messages mentioning that the process was terminated due to `std::bad_alloc`?

**Comment by Kincaidr** [comment]
I am getting an error related to this issue:

```
INFO      11:53:06 - data_handler       [x01] [10.3/11.2 23.5/36.2 9.3Gb] reading FLAG
INFO      11:53:11 - data_handler       [x01] [12.1/13.0 24.1/36.8 9.3Gb] reading BITFLAG
INFO      11:53:31 - ms_tile            [x01] [16.3/17.2 28.2/41.0 9.3Gb]   83.96% input visibilities flagged and/or deselected
INFO      11:53:37 - data_handler       [x01] [17.5/18.4 53.3/66.0 17.7Gb] reading MODEL_DATA
INFO      11:53:49 - main               [0.9 12.7 22.5Gb] Exiting with exception: BrokenProcessPool(A process in the process pool was terminated abruptly while the future was running or pending.)
 Traceback (most recent call last):
  File "/home/kincaid/Software/CubiCal/cubical/main.py", line 578, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/kincaid/Software/CubiCal/cubical/workers.py", line 226, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/kincaid/Software/CubiCal/cubical/workers.py", line 286, in _run_multi_process_loop
    if not io_futures[itile].result():
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```
I am not using a tigger LSM, only regions file and DicoModel: `--model-list MODEL_DATA+-image_DI_beam_2poly_b
eam_zwcl.DicoModel@A2631_4sources.reg:image_DI_beam_2poly_beam_zwcl.DicoModel@A2631_4sources.reg`

I have also tried running in serial mode `--dist-ncpu 1` and lowering time chunk`--data-time-chunk 10` but still same error.

full log file: [ddcal_0.log](https://github.com/ratt-ru/CubiCal/files/6878186/ddcal_0.log)

**Comment by o-smirnov** [comment]
Hmmm, from the log it doesn't seem to go fully serial. Try ``--dist-ncpu 1 --dist-nworker 0 --dist-nthread 0`` for true serial, and post the log please.

**Comment by Kincaidr** [comment]
```
INFO      14:57:12 - data_handler       [0.9 13.7 9.3Gb]   will save output flags into BITFLAG 'cubical' (2), and into FLAG/FLAG_ROW
INFO      14:57:12 - ms_tile            [0.9 13.7 9.3Gb] tile 0/22: reading MS rows 0~195299
INFO      14:57:12 - data_handler       [0.9 13.7 9.3Gb] reading CORRECTED_DATA
INFO      14:57:21 - data_handler       [10.4 24.4 9.3Gb] reading FLAG
INFO      14:57:26 - data_handler       [12.2 25.0 9.3Gb] reading BITFLAG
INFO      14:57:46 - ms_tile            [16.4 29.2 9.3Gb]   83.96% input visibilities flagged and/or deselected
INFO      14:57:52 - data_handler       [17.6 54.2 17.7Gb] reading MODEL_DATA
semaphore initilization: Permission denied
```
Full log: [ddcal_0.log](https://github.com/ratt-ru/CubiCal/files/6878329/ddcal_0.log)

**Comment by o-smirnov** [comment]
Woah, that's a new one. Smells like a shared memory issue to me though. Which machine are you on?

**Comment by Kincaidr** [comment]
crosby

**Comment by Kincaidr** [comment]
It is running, and still has not terminated. What did you change?

**Comment by o-smirnov** [comment]
I cleaned up a bunch of old semaphores under /dev/shm.

**Comment by Sinah-astro** [comment]
> I cleaned up a bunch of old semaphores under /dev/shm.

I'm also getting an error related to Robert's. I'm looking at the directory on my machine (oates) and I'm clueless on what could be old here
