### ISSUE TITLE
Masked Array causes problems in plotting code

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#72]
Something I ran into for the first time today.

Exiting with exception: AttributeError('MaskedConstant' object has no attribute '_fill_value')
 Traceback (most recent call last):
  File "/home/jonathan/CubiCal/cubical/main.py", line 368, in main
    flag3 = flagging.flag_chisq(st, GD, basename, ms.nddid)
  File "/home/jonathan/CubiCal/cubical/flagging.py", line 324, in flag_chisq
    pylab.savefig(filename, DPI=plots.DPI)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/image.py", line 548, in draw
    renderer, renderer.get_image_magnification())
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/image.py", line 774, in make_image
    unsampled=unsampled)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/matplotlib/image.py", line 370, in _make_image
    a_min = np.ma.min(A).astype(scaled_dtype)
  File "/home/jonathan/venvs/newsetupenv/local/lib/python2.7/site-packages/numpy/ma/core.py", line 3205, in astype
    if self._fill_value is not None:
AttributeError: 'MaskedConstant' object has no attribute '_fill_value'

This is [mentioned on the Numpy repo](https://github.com/numpy/numpy/issues/4595).

@o-smirnov No idea why this is suddenly a problem - seems as though it may be in master. Was the plotting code changed at some point?

**Comment by o-smirnov** [comment]
I haven't touched the chisq plotting code in ages. This must be some edge case we haven't tripped on before. Can you give me a recipe to replicate this?

If I had to make a bet, I'd say it's trying to plot something that is completely flagged (i.e. a fully masked array). In which case we just need to check for this before plotting.

**Comment by o-smirnov** [comment]
And looks I would lose that bet. The failing plot is made here: https://github.com/ratt-ru/CubiCal/blob/master/cubical/flagging.py#L320. I tried to make an all-flagged version of ``chi2`` by
fiddling with the assignment at https://github.com/ratt-ru/CubiCal/blob/master/cubical/flagging.py#L317, but it just plotted an empty white box, as it ought to.

@JSKenyon if you can't point me at an MS/parset to reproduce it, can you please add ``print>>log(0),(chi2, chi2.shape)`` to just before the plotting statement? My next theory is that chi2 has contrived to become a single constant number.

**Comment by JSKenyon** [comment]
Sorry - working on getting you a reproducible case. Struggling due to the tigger dependency and vext causing all output to disappear. Known issue, now made worse by the fact that astro-tigger installs vext in a virtualenv. My own fault for requesting it, but I have no idea what unholy interaction is in play.

**Comment by JSKenyon** [comment]
MS is in my home on aretha, in folder called bug_hunt. Run with default parset and:

```
gocubical --data-ms WSRT_PO.MS --model-column MODEL_DATA --weight-column ""
```

**Comment by JSKenyon** [comment]
@o-smirnov I am not even 100% sure that it is reproducible. I would suggest trying it regardless, but perhaps I had some odd/corrupted data.

**Comment by o-smirnov** [comment]
If I log in as you to test this, which venv do I need to activate?

**Comment by JSKenyon** [comment]
I didn't run it on aretha - you may need to do your own install there.

**Comment by JSKenyon** [comment]
Ok @o-smirnov, this is now reproducible. Have run it on Aretha, now that I have restored the logging. The virtualenv you need is called bugenv and is in the same directory as the MS.

**Comment by o-smirnov** [comment]
Good, because it's not reproducible on my laptop... will take a look.

**Comment by o-smirnov** [comment]
OK, I win my bet with myself after all. It seems that some versions of numpy and/or matplotlib fall over and cry when asked to ``imshow()`` a fully-masked array (while others plot an empty box, as they should). I have added a simple check to avoid this problem.

**Comment by JSKenyon** [comment]
Cool - definitely working. Thanks!
